name: torr_distribution
description: Torr Distribution Picker App (Location session + Product scan)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  permission_handler: ^11.0.0
  google_mlkit_barcode_scanning: ^0.14.1
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  csv: ^6.0.0
  uuid: ^4.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/products.csv
    - assets/data/pick_tasks.csv
    - assets/data/location_barcodes.csv
